
version: '3'

services:

  nats-servers:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/manifest-access-428916-p6/image-registry/client-gateway
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
      - NATS_SERVERS=nats://nats-servers:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/manifest-access-428916-p6/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/manifest-access-428916-p6/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=file:./dev.db

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/manifest-access-428916-p6/image-registry/payments-ms
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - NATS_SERVERS=nats://nats-servers:4222
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}


  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DATABASE=${ORDERS_MS_DATABASE}
    image: europe-southwest1-docker.pkg.dev/manifest-access-428916-p6/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE}

  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports: 
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb
  


